<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<script src='https://arsenalpay.ru/widget/script.js'></script>
<div id='app-widget'></div>
 <script> 
    var APWidget = new ArsenalpayWidget({
        element: 'app-widget',
        destination: "<?= $variables['purchase']['purchasing']['destination'] ?>",
        widget: "<?= $variables['purchase']['purchasing']['widget'] ?>",
        amount: "<?= $variables['purchase']['purchasing']['amount'] ?>",
        userId: "<?= $variables['purchase']['purchasing']['userId'] ?>",
        nonce: "<?= $variables['purchase']['purchasing']['nonce'] ?>",
        widgetSign: "<?= $variables['purchase']['purchasing']['widgetSign'] ?>"
    });
    APWidget.render();
</script>
